blank_issues_enabled: true
contact_links:
  - name: CitusData Contact Form
    url: https://www.citusdata.com/about/contact_us
    about: We'd love to hear from you
  - name: Join our Slack channel
    url: https://slack.citusdata.com/
    about: For chatting with Citus users & hackers 
  - name: Follow us on twitter
    url: https://www.twitter.com/citusdata
    about: Keep yourself in the loop
    
